<template>
	<div>
		<city-header :city="adress"></city-header>
		<city-recity :letterb="lettera" :city="ucity"></city-recity>
		<city-alphabet @change='changea'></city-alphabet>
	</div>
</template>

<script>
import CityHeader from './components/Header'
import CityRecity from './components/Recity'
import CityAlphabet from './components/Alphabet'
export default {
	name:"City",
	data (){
		return{
			lettera:' ',
			ucity:[{
				'id':'001',
				'ucity':'北京'
			},{
				'id':'002',
				'ucity':'上海'
			},{
				'id':'003',
				'ucity':'重庆'
			},{
				'id':'004',
				'ucity':'成都'
			},{
				'id':'005',
				'ucity':'三亚'
			},{
				'id':'006',
				'ucity':'拉萨'
			},{
				'id':'007',
				'ucity':'广州'
			},{
				'id':'009',
				'ucity':'天津'
			},{
				'id':'008',
				'ucity':'深圳'
			}],
			'adress':{
				'A':[{
					'id':'1',
					'name':'爱丽丝'
				},{
					'id':'2',
					'name':'阿第克'
				},{
					'id':'3',
					'name':'安东诺夫'
				}],
				'B':[{
					'id':'4',
					'name':'爱丽丝'
				},{
					'id':'5',
					'name':'阿第克'
				},{
					'id':'6',
					'name':'安东诺夫'
				}],
				'C':[{
					'id':'7',
					'name':'爱丽丝'
				},{
					'id':'8',
					'name':'阿第克'
				},{
					'id':'9',
					'name':'安东诺夫'
				}],
				'D':[{
					'id':'10',
					'name':'爱丽丝'
				},{
					'id':'11',
					'name':'阿第克'
				},{
					'id':'12',
					'name':'安东诺夫'
				}],
				'E':[{
					'id':'13',
					'name':'爱丽丝'
				},{
					'id':'14',
					'name':'阿第克'
				},{
					'id':'15',
					'name':'安东诺夫'
				}],
				'F':[{
					'id':'16',
					'name':'爱丽丝'
				},{
					'id':'17',
					'name':'阿第克'
				},{
					'id':'18',
					'name':'安东诺夫'
				}],
				'G':[{
					'id':'19',
					'name':'爱丽丝'
				},{
					'id':'20',
					'name':'阿第克'
				},{
					'id':'21',
					'name':'安东诺夫'
				}],
				'H':[{
					'id':'22',
					'name':'爱丽丝'
				},{
					'id':'77',
					'name':'阿第克'
				},{
					'id':'23',
					'name':'安东诺夫'
				}],
				'I':[{
					'id':'24',
					'name':'爱丽丝'
				},{
					'id':'78',
					'name':'阿第克'
				},{
					'id':'25',
					'name':'安东诺夫'
				}],
				'J':[{
					'id':'26',
					'name':'爱丽丝'
				},{
					'id':'27',
					'name':'阿第克'
				},{
					'id':'28',
					'name':'安东诺夫'
				}],
				'K':[{
					'id':'29',
					'name':'爱丽丝'
				},{
					'id':'30',
					'name':'阿第克'
				},{
					'id':'31',
					'name':'安东诺夫'
				}],
				'L':[{
					'id':'32',
					'name':'爱丽丝'
				},{
					'id':'33',
					'name':'阿第克'
				},{
					'id':'34',
					'name':'安东诺夫'
				}],
				'M':[{
					'id':'35',
					'name':'爱丽丝'
				},{
					'id':'36',
					'name':'阿第克'
				},{
					'id':'37',
					'name':'安东诺夫'
				}],
				'N':[{
					'id':'38',
					'name':'爱丽丝'
				},{
					'id':'39',
					'name':'阿第克'
				},{
					'id':'40',
					'name':'安东诺夫'
				}],
				'O':[{
					'id':'41',
					'name':'爱丽丝'
				},{
					'id':'42',
					'name':'阿第克'
				},{
					'id':'43',
					'name':'安东诺夫'
				}],
				'P':[{
					'id':'44',
					'name':'爱丽丝'
				},{
					'id':'45',
					'name':'阿第克'
				},{
					'id':'46',
					'name':'安东诺夫'
				}],
				'Q':[{
					'id':'47',
					'name':'爱丽丝'
				},{
					'id':'48',
					'name':'阿第克'
				},{
					'id':'49',
					'name':'安东诺夫'
				}],
				'R':[{
					'id':'50',
					'name':'爱丽丝'
				},{
					'id':'51',
					'name':'阿第克'
				},{
					'id':'52',
					'name':'安东诺夫'
				}],
				'S':[{
					'id':'53',
					'name':'爱丽丝'
				},{
					'id':'54',
					'name':'阿第克'
				},{
					'id':'55',
					'name':'安东诺夫'
				}],
				'T':[{
					'id':'56',
					'name':'爱丽丝'
				},{
					'id':'57',
					'name':'阿第克'
				},{
					'id':'58',
					'name':'安东诺夫'
				}],
				'U':[{
					'id':'59',
					'name':'爱丽丝'
				},{
					'id':'6',
					'name':'阿第克'
				},{
					'id':'61',
					'name':'安东诺夫'
				}],
				'V':[{
					'id':'62',
					'name':'爱丽丝'
				},{
					'id':'63',
					'name':'阿第克'
				},{
					'id':'64',
					'name':'安东诺夫'
				}],
				'W':[{
					'id':'65',
					'name':'爱丽丝'
				},{
					'id':'66',
					'name':'阿第克'
				},{
					'id':'67',
					'name':'安东诺夫'
				}],
				'X':[{
					'id':'68',
					'name':'爱丽丝'
				},{
					'id':'69',
					'name':'阿第克'
				},{
					'id':'70',
					'name':'安东诺夫'
				}],
				'Y':[{
					'id':'71',
					'name':'爱丽丝'
				},{
					'id':'72',
					'name':'阿第克'
				},{
					'id':'73',
					'name':'安东诺夫'
				}],
				'Z':[{
					'id':'74',
					'name':'爱丽丝'
				},{
					'id':'75',
					'name':'阿第克'
				},{
					'id':'76',
					'name':'安东诺夫'
				}]
			}
		}
	},
	components:{
		CityHeader,
		CityRecity,
		CityAlphabet
	},
	methods:{
		changea(letter){
			this.lettera=letter
		}
	}
}
</script>

<style scoped>

</style>