document.writeln('<div class="top_box">');
document.writeln('   <span>第<em id="now_qishu">-----------</em>期</span>');
document.writeln('   <p id="show_qiu">');
document.writeln("     <em></em>");
document.writeln("     <em></em>");
document.writeln("     <em></em>");
document.writeln("     <em></em>");
document.writeln("     <em></em>");
document.writeln("\t ");
document.writeln("   </p>");
document.writeln('   <i class="fa fa-question-circle-o"></i>');
document.writeln("</div>");
document.writeln("");
document.writeln('<div class="xiaqi_box" id="xiaqi_box" >');
document.writeln("\t");
document.writeln('\t<span class="qishu_box" style="width:100%;text-align: center;" >正在更新个位计划，请稍后...</span>');
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln('<div class="index_box">');
document.writeln('  <div class="left_box"></div>');
document.writeln("  ");
document.writeln('  <div class="left_box">');
document.writeln('       <div class="jihuay jihuay_f" style="margin-top: 0px;" onClick="window.location.href=\'game/?id=5&t=1&m=1\';">');
document.writeln('          <i class="fa fa-soccer-ball-o"></i><span><em>五分彩</em></span>');
document.writeln("       </div>");
document.writeln('       <div class="jihuay jihuay_a" onClick="window.location.href=\'game/?id=1&t=1&m=1\';">');
document.writeln('          <i class="fa fa-car"></i><span><em>重庆时时彩</em></span>');
document.writeln("       </div>");
document.writeln('       <div class="jihuay jihuay_b" onClick="window.location.href=\'game/?id=2&t=1&m=2\';">');
document.writeln('          <i class="fa fa-soccer-ball-o"></i><span><em>北京赛车PK10</em></span>');
document.writeln("       </div>");
document.writeln('       <div class="jihuay jihuay_c" onClick="window.location.href=\'game/?id=3&t=1&m=1\';">');
document.writeln('          <i class="fa fa-soccer-ball-o"></i><span><em>分分彩</em></span>');
document.writeln("       </div>");
document.writeln('       <div class="jihuay jihuay_d" onClick="window.location.href=\'game/?id=6&t=1&m=1\';">');
document.writeln('          <i class="fa fa-soccer-ball-o"></i><span><em>PC蛋蛋</em></span>');
document.writeln("       </div>");
document.writeln('       <div class="jihuay jihuay_e" onClick="window.location.href=\'game/?id=4&t=1&m=1\';">');
document.writeln('          <i class="fa fa-soccer-ball-o"></i><span><em>二分彩</em></span>');
document.writeln("       </div>");
document.writeln('\t   <div class="jihuay jihuay_e" style="background-color:#ff7402" onClick="window.location.href=\'game/?id=10&t=1&m=2\';">');
document.writeln('        <i class="fa fa-soccer-ball-o"></i>');
document.writeln("        <span>");
document.writeln("          <em>极速赛车</em>");
document.writeln("        </span>");
document.writeln("      </div>");
document.writeln("  </div>");
document.writeln("  ");
document.writeln("  ");
document.writeln('  <div class="right_box">');
document.writeln('       <div class="remen_box">');
document.writeln('            <div class="top_remen"><i class="fa fa-volume-up"></i>最新公告</div><div class="clear"></div>');
document.writeln("            <ul>");
document.writeln('\t\t\t\t<li class="cssellipsis" id="remenhao"></li>');
document.writeln('\t\t\t\t<li><a href="mqqwpa://im/chat?chat_type=wpa&uin=825159999&version=1&src_type=web&web_src=557799.com" style="color:#fff" target="_blank">联系不到自己上级的  想代理加盟黄金8平台的  请联系QQ：825159999</a></li>');
document.writeln("\t\t\t\t<li>请到平台获取最近充值二维码</li>");
document.writeln("\t\t\t</ul>");
document.writeln("       </div>");
document.writeln('\t   <div id="regurl" class="jihuay jihuay_l" onClick="window.location.href=\'http://hj8dl.com/\';">');
document.writeln('          <i class="fa fa-user-plus"></i><span><em>代理加盟</em></span>');
document.writeln("       </div>");
document.writeln('       <div id="urlb" class="jihuay jihuay_j" onClick="window.location.href=\'https://tb.53kf.com/code/client/10166899/1\';">');
document.writeln('          <i class="fa fa-user-o"></i><span><em>平台客服</em></span>');
document.writeln("       </div>");
document.writeln('       <div id="loginurl" class="jihuay jihuay_k" onClick="window.location.href=\'http://22hj8.com\';">');
document.writeln('          <i class="fa fa-user-circle"></i><span><em>登录平台</em></span>');
document.writeln("       </div>");
document.writeln('       <div id="regurl" class="jihuay jihuay_l" onClick="window.location.href=\'http://8760000.cc/registerMutil/link_36999.do\';">');
document.writeln('          <i class="fa fa-user-plus"></i><span><em>注册账号</em></span>');
document.writeln("       </div>");
document.writeln("");
document.writeln("");
document.writeln("  </div>");
document.writeln('  <div class="clear"></div>');
document.writeln('\t<input id="multiple" type="hidden" value="0">');
document.writeln("</div>");
document.writeln('<div class="foot_box">');
document.writeln("  \t© 2009-2019 557799.com. All rights reserved.");
document.writeln("</div>");
document.writeln('<script language="javascript" src="js/open_time.js?v=7"></script>');
document.writeln('<script language="javascript" src="js/tongji.js?v=5"></script>');
document.writeln("<script>");
document.writeln("\t\t");
document.writeln('\t\tGameType="SSCINDEX";');
document.writeln('\t\tvar ApiUrl="http://47.90.100.194:8090";');
document.writeln("\t\t$(document).ready(function () {");
document.writeln("\t\tStartRun();");
document.writeln("\t\t});");
document.writeln("");
document.writeln("</script>");
document.writeln("<script>");
document.writeln("$('.top_box').find('i').click(function(){");
document.writeln('   alert(\'全天时时彩计划说明//r//n全天时时彩计划软件只计划定位胆个位，由人工手动发布至网站，可能每期计划号码的发布时间有1-10秒时间差。"5码3期计划"适用于加奖70%至93%的时时彩，若加奖太低可能无法赢利，若太高可能是小黑平台引诱骗钱。//r//n什么是"5码3期计划"？ //r//n在时时彩→定位胆玩法→个位，根据计划员提供的5个号码，在个位选择相同的5个号进行购买，中了换号码，不中继续倍投。此为"5码3期计划"，是目前加奖时时彩概率最高的人工计划与玩法。//r//n重点：七位计划员提供的计划号码仅适用于倍投模式，连续3期购买一组计划号码，若中奖将会更换计划号码，若未中奖，请按下面倍投公式翻倍继续跟计划号码，如果连续3期计划都未中，计划员将会更换新的一组计划号码，继续进行倍投。倍投期间请勿停止翻倍，什么时候倍投中了，什么时候停止翻倍，否则全部亏损。//r//n倍投公式：1倍 3倍 8倍 24倍 72倍 216倍 648倍 1944倍 5832倍 17496倍\');\t');
document.writeln("});");
document.writeln("</script>");